# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='com.akolar.maxaltitude',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\x12\x16\x63om.akolar.maxaltitude\"\xed\x07\n\x0e\x41ircraftBeacon\x12\x14\n\x0cmessage_from\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65stto\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x16 \x01(\x02\x12\x10\n\x08receiver\x18\x06 \x01(\t\x12\x0b\n\x03uid\x18\x07 \x01(\t\x12\x0f\n\x07stealth\x18\x08 \x01(\x08\x12\x14\n\x0c\x64o_not_track\x18\t \x01(\x08\x12\x13\n\x0braw_message\x18\x13 \x01(\t\x12\x0f\n\x07relayer\x18\n \x01(\t\x12\x0f\n\x07heading\x18\x0b \x01(\r\x12\x14\n\x0cground_speed\x18\x0c \x01(\x02\x12\x16\n\x0evertical_speed\x18\r \x01(\x02\x12\x11\n\tturn_rate\x18\x0e \x01(\x02\x12\x1d\n\x15signal_to_noise_ratio\x18\x0f \x01(\x02\x12\x13\n\x0b\x65rror_count\x18\x10 \x01(\r\x12\x13\n\x0b\x66req_offset\x18\x11 \x01(\x02\x12J\n\raircraft_type\x18\x14 \x01(\x0e\x32\x33.com.akolar.maxaltitude.AircraftBeacon.AircraftType\x12H\n\x0c\x61\x64\x64ress_type\x18\x15 \x01(\x0e\x32\x32.com.akolar.maxaltitude.AircraftBeacon.AddressType\x12\x43\n\x0bgps_quality\x18\x12 \x01(\x0b\x32..com.akolar.maxaltitude.AircraftBeacon.Quality\x1a/\n\x07Quality\x12\x12\n\nhorizontal\x18\x01 \x01(\r\x12\x10\n\x08vertical\x18\x02 \x01(\r\"\x80\x02\n\x0c\x41ircraftType\x12\x14\n\x10UNKNOWN_AIRPLANE\x10\x00\x12\n\n\x06GLIDER\x10\x01\x12\r\n\tTOW_PLANE\x10\x02\x12\x19\n\x15HELICOPTER_ROTORCRAFT\x10\x03\x12\r\n\tPARACHUTE\x10\x04\x12\x0e\n\nDROP_PLANE\x10\x05\x12\x0f\n\x0bHANG_GLIDER\x10\x06\x12\x0e\n\nPARAGLIDER\x10\x07\x12\x14\n\x10POWERED_AIRCRAFT\x10\x08\x12\x10\n\x0cJET_AIRCRAFT\x10\t\x12\x07\n\x03UFO\x10\n\x12\n\n\x06\x42\x41LOON\x10\x0b\x12\x0b\n\x07\x41IRSHIP\x10\x0c\x12\x07\n\x03UAV\x10\r\x12\x11\n\rSTATIC_OBJECT\x10\x0f\"U\n\x0b\x41\x64\x64ressType\x12\x13\n\x0fUNKNOWN_ADDRESS\x10\x00\x12\x08\n\x04ICAO\x10\x01\x12\t\n\x05\x46LARM\x10\x02\x12\x0f\n\x0bOGN_TRACKER\x10\x03\x12\x0b\n\x07NAVITER\x10\x04\x62\x06proto3')
)



_AIRCRAFTBEACON_AIRCRAFTTYPE = _descriptor.EnumDescriptor(
  name='AircraftType',
  full_name='com.akolar.maxaltitude.AircraftBeacon.AircraftType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_AIRPLANE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GLIDER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOW_PLANE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HELICOPTER_ROTORCRAFT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARACHUTE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DROP_PLANE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HANG_GLIDER', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARAGLIDER', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWERED_AIRCRAFT', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JET_AIRCRAFT', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UFO', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BALOON', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AIRSHIP', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UAV', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATIC_OBJECT', index=14, number=15,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=704,
  serialized_end=960,
)
_sym_db.RegisterEnumDescriptor(_AIRCRAFTBEACON_AIRCRAFTTYPE)

_AIRCRAFTBEACON_ADDRESSTYPE = _descriptor.EnumDescriptor(
  name='AddressType',
  full_name='com.akolar.maxaltitude.AircraftBeacon.AddressType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ADDRESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICAO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLARM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OGN_TRACKER', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAVITER', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=962,
  serialized_end=1047,
)
_sym_db.RegisterEnumDescriptor(_AIRCRAFTBEACON_ADDRESSTYPE)


_AIRCRAFTBEACON_QUALITY = _descriptor.Descriptor(
  name='Quality',
  full_name='com.akolar.maxaltitude.AircraftBeacon.Quality',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='horizontal', full_name='com.akolar.maxaltitude.AircraftBeacon.Quality.horizontal', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertical', full_name='com.akolar.maxaltitude.AircraftBeacon.Quality.vertical', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=701,
)

_AIRCRAFTBEACON = _descriptor.Descriptor(
  name='AircraftBeacon',
  full_name='com.akolar.maxaltitude.AircraftBeacon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_from', full_name='com.akolar.maxaltitude.AircraftBeacon.message_from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destto', full_name='com.akolar.maxaltitude.AircraftBeacon.destto', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.akolar.maxaltitude.AircraftBeacon.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='com.akolar.maxaltitude.AircraftBeacon.latitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='com.akolar.maxaltitude.AircraftBeacon.longitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='com.akolar.maxaltitude.AircraftBeacon.altitude', index=5,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='com.akolar.maxaltitude.AircraftBeacon.receiver', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='com.akolar.maxaltitude.AircraftBeacon.uid', index=7,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stealth', full_name='com.akolar.maxaltitude.AircraftBeacon.stealth', index=8,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='do_not_track', full_name='com.akolar.maxaltitude.AircraftBeacon.do_not_track', index=9,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_message', full_name='com.akolar.maxaltitude.AircraftBeacon.raw_message', index=10,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relayer', full_name='com.akolar.maxaltitude.AircraftBeacon.relayer', index=11,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='com.akolar.maxaltitude.AircraftBeacon.heading', index=12,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ground_speed', full_name='com.akolar.maxaltitude.AircraftBeacon.ground_speed', index=13,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertical_speed', full_name='com.akolar.maxaltitude.AircraftBeacon.vertical_speed', index=14,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn_rate', full_name='com.akolar.maxaltitude.AircraftBeacon.turn_rate', index=15,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal_to_noise_ratio', full_name='com.akolar.maxaltitude.AircraftBeacon.signal_to_noise_ratio', index=16,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_count', full_name='com.akolar.maxaltitude.AircraftBeacon.error_count', index=17,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freq_offset', full_name='com.akolar.maxaltitude.AircraftBeacon.freq_offset', index=18,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aircraft_type', full_name='com.akolar.maxaltitude.AircraftBeacon.aircraft_type', index=19,
      number=20, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_type', full_name='com.akolar.maxaltitude.AircraftBeacon.address_type', index=20,
      number=21, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gps_quality', full_name='com.akolar.maxaltitude.AircraftBeacon.gps_quality', index=21,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AIRCRAFTBEACON_QUALITY, ],
  enum_types=[
    _AIRCRAFTBEACON_AIRCRAFTTYPE,
    _AIRCRAFTBEACON_ADDRESSTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=1047,
)

_AIRCRAFTBEACON_QUALITY.containing_type = _AIRCRAFTBEACON
_AIRCRAFTBEACON.fields_by_name['aircraft_type'].enum_type = _AIRCRAFTBEACON_AIRCRAFTTYPE
_AIRCRAFTBEACON.fields_by_name['address_type'].enum_type = _AIRCRAFTBEACON_ADDRESSTYPE
_AIRCRAFTBEACON.fields_by_name['gps_quality'].message_type = _AIRCRAFTBEACON_QUALITY
_AIRCRAFTBEACON_AIRCRAFTTYPE.containing_type = _AIRCRAFTBEACON
_AIRCRAFTBEACON_ADDRESSTYPE.containing_type = _AIRCRAFTBEACON
DESCRIPTOR.message_types_by_name['AircraftBeacon'] = _AIRCRAFTBEACON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AircraftBeacon = _reflection.GeneratedProtocolMessageType('AircraftBeacon', (_message.Message,), dict(

  Quality = _reflection.GeneratedProtocolMessageType('Quality', (_message.Message,), dict(
    DESCRIPTOR = _AIRCRAFTBEACON_QUALITY,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:com.akolar.maxaltitude.AircraftBeacon.Quality)
    ))
  ,
  DESCRIPTOR = _AIRCRAFTBEACON,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:com.akolar.maxaltitude.AircraftBeacon)
  ))
_sym_db.RegisterMessage(AircraftBeacon)
_sym_db.RegisterMessage(AircraftBeacon.Quality)


# @@protoc_insertion_point(module_scope)
